Repository chukwuemekachm/utility_manager_web, pull requests merged in 2020-01, with the labels that each got.

#8 Prof: Adding forgot password logic to UI
  package-lock.json
  src/components/containers/AuthenticationContainer/index.ts
  src/components/layouts/AuthenticationLayout/index.stories.tsx
  src/components/layouts/Footer/index.stories.tsx
  src/components/layouts/Logo/index.stories.tsx
  src/components/layouts/Logo/index.tsx
  src/components/pages/Authentication/ForgotPassword/ForgotPassword.tsx
  src/components/pages/Authentication/ForgotPassword/index.tsx
  src/components/pages/Authentication/Login/LoginForm.tsx
  src/components/pages/Authentication/Login/index.tsx
  src/components/pages/Authentication/SignUp/SignUpForm.tsx
  src/components/pages/Authentication/index.tsx
  src/components/pages/ConfirmResetPassword/NewPassword/index.tsx
  src/components/pages/ConfirmResetPassword/index.tsx
  src/components/ui/Button/index.stories.tsx
  src/components/ui/Button/index.tsx
  src/components/ui/EmailSentSuccess/index.stories.tsx
  src/components/ui/EmailSentSuccess/index.tsx
  src/components/ui/Loader/index.stories.tsx
  src/lib/validator/schemas.ts
  src/services/api/request.ts
  src/store/actions/auth/constants.ts
  src/store/actions/auth/index.ts
  src/store/reducers/auth.ts
  src/store/sagas/auth.ts
Labels: Awaiting Review

#11 Prof: Fix ConfirmResetPassword page
  package-lock.json
  src/components/containers/AuthenticationContainer/index.ts
  src/components/layouts/AuthenticationFormLayout/index.stories.tsx
  src/components/layouts/AuthenticationFormLayout/index.tsx
  src/components/layouts/AuthenticationLayout/index.stories.tsx
  src/components/layouts/AuthenticationLayout/index.tsx
  src/components/layouts/Footer/index.tsx
  src/components/pages/Authentication/Login/LoginForm.tsx
  src/components/pages/Authentication/Login/index.tsx
  src/components/pages/Authentication/SignUp/SignUpForm.tsx
  src/components/pages/Authentication/SignUp/index.tsx
  src/components/pages/Authentication/index.tsx
  src/components/pages/ConfirmResetPassword/NewPassword/index.tsx
  src/components/pages/ConfirmResetPassword/index.tsx
  src/components/ui/Checkbox/index.stories.tsx
  src/components/ui/Checkbox/index.tsx
  src/components/ui/Input/index.stories.tsx
  src/components/ui/Input/index.tsx
  src/components/ui/Link/index.tsx
  src/lib/validator/schemas.ts
  src/services/api/request.ts
  src/settings/__color.ts
  src/store/actions/auth/index.ts
  src/store/reducers/auth.ts
  src/store/sagas/auth.ts
  yarn.lock
Labels: Awaiting Review

#14 Prof: Ensures api calls work as expected with Cookie infrastructure
  src/components/containers/AuthenticationContainer/index.ts
  src/components/pages/Authentication/Login/LoginForm.tsx
  src/components/pages/Authentication/SignUp/SignUpForm.tsx
  src/components/pages/ConfirmResetPassword/index.tsx
  src/components/pages/Dashboard/index.tsx
  src/components/pages/index.tsx
  src/components/ui/Checkbox/index.tsx
  src/components/ui/Input/index.tsx
  src/services/api/index.ts
  src/services/api/request.ts
  src/store/actions/dashboard/constants.ts
  src/store/actions/dashboard/index.ts
  src/store/reducers/dashboard.ts
  src/store/reducers/index.ts
  src/store/sagas/auth.ts
  src/store/sagas/dashboard.ts
  src/store/sagas/index.ts
Labels: Complete

#15 Prof: implement continuous integration using circleci
  .circleci/config.yml
  README.md
  package-lock.json
  package.json
  src/components/containers/AuthenticationContainer/index.ts
  src/components/layouts/AuthenticationFormLayout/index.stories.tsx
  src/components/layouts/AuthenticationFormLayout/index.tsx
  src/components/pages/Authentication/SignUp/SignUpForm.tsx
  src/components/ui/Loader/index.tsx
Labels: Complete

#16 Xrole: create reusable organisation card component
  .storybook/preview-head.html
  src/components/ui/OrganisationCard/index.stories.tsx
  src/components/ui/OrganisationCard/index.tsx
  src/settings/__color.ts
  yarn.lock
Labels: Awaiting Review, Complete

#19 Xrole: user should be able to view their organisations on their dashboard and click on it to go their organisational page
  src/components/layouts/DashBoardLayout/index.tsx
  src/components/pages/Dashboard/index.tsx
  src/components/pages/MyOrganisations/index.tsx
  src/components/ui/OrganisationCard/index.tsx
  src/helpers/dateHelpers.ts
  src/services/api/request.ts
  src/store/actions/dashboard/constants.ts
  src/store/actions/dashboard/index.ts
  src/store/reducers/dashboard.ts
  src/store/sagas/dashboard.ts
Labels: Awaiting Review
